name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: black --check src tests || true
      - run: flake8 src tests || true
      - run: pytest -q || true
